name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  verify:
    uses: yohn-jp/.github/.github/workflows/go-ci.yml@main
    permissions:
      contents: read
